apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "icinga2.fullname" . }}
  labels:
    {{- include "icinga2.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "icinga2.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "icinga2.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "icinga2.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "icinga2.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: api
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          command:
            - icinga2
            - daemon
          volumeMounts:
            - name: data
              mountPath: /data
            - name: {{ include "icinga2.fullname" . }}-features
              mountPath: /etc/icinga2/features-enabled
            - name: {{ include "icinga2.fullname" . }}-config
              mountPath: /etc/icinga2
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      initContainers:
        - name: {{ .Chart.Name }}-bootstrapper
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - icinga2
            - daemon
            - -C
          env:
            - name: ICINGA_CN
              value: {{ .Values.config.node_name | quote }}
            - name: ICINGA_MASTER
              value: "1"
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: {{ include "icinga2.fullname" . }}-features
          configMap:
            name: {{ include "icinga2.fullname" . }}-features
        - name: {{ include "icinga2.fullname" . }}-config
          configMap:
            name: {{ include "icinga2.fullname" . }}-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
