kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: icinga2-master
  labels:
    {{- include "icinga2.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi