name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - mocdaniel
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please try
        to fill out as much of the information below as you can.
  - type: dropdown
    id: chart
    attributes:
      label: Affected Chart
      description: Which chart is this bug report referring to?
      options:
        - icinga-stack
        - icinga2
        - icingadb
        - icingaweb2
    validations:
      required: true
  - type: input
    id: app_version
    attributes:
      label: Which version of the app contains the bug?
      description: If you're not sure, you can find this by running `helm list` under the "APP_VERSION"
      placeholder: 1.16.0
  - type: textarea
    id: description
    attributes:
      label: Please describe your problem
      description: Please provide a concise description of the bug copy and paste any relevant log output. You can use markdown syntax for formatting.
